/* Creation local database user*/
CREATE USER CLOTHESSTORE IDENTIFIED BY A CONTAINER=CURRENT;

ALTER USER CLOTHESSTORE ACCOUNT UNLOCK;

GRANT CONNECT, RESOURCE TO CLOTHESSTORE;

/* Sequences */
CREATE SEQUENCE CLOTHESSTORE.S_PRODUCT MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;

/* Tables */
CREATE TABLE CLOTHESSTORE.PRODUCT (
  ID            NUMBER(12) DEFAULT CLOTHESSTORE.S_PRODUCT.NEXTVAL NOT NULL
 ,NAME          VARCHAR2(100 CHAR)                                NOT NULL
 ,DESCRIPTION   VARCHAR2(200 CHAR)
 ,PRICE         NUMBER(10,3)                                      NOT NULL
 ,RATEDISCOUNT  NUMBER(2) DEFAULT 0                               NOT NULL
 ,IMAGEFRONT    CLOB      DEFAULT EMPTY_CLOB()
 ,IMAGEBACK     CLOB      DEFAULT EMPTY_CLOB()
 ,POPULARSEARCH NUMBER(1) DEFAULT 0                               NOT NULL
 ,CONSTRAINT PK_PRODUCT PRIMARY KEY (ID) USING INDEX
);

COMMENT ON TABLE CLOTHESSTORE.PRODUCT IS 'Contiene información del producto.';

COMMENT ON COLUMN CLOTHESSTORE.PRODUCT.ID IS 'Id del producto.';
COMMENT ON COLUMN CLOTHESSTORE.PRODUCT.NAME IS 'Nombre del producto.';
COMMENT ON COLUMN CLOTHESSTORE.PRODUCT.DESCRIPTION IS 'Descripción del producto.';
COMMENT ON COLUMN CLOTHESSTORE.PRODUCT.PRICE IS 'Precio del producto.';
COMMENT ON COLUMN CLOTHESSTORE.PRODUCT.RATEDISCOUNT IS 'Porcentaje de descuento (0 a 100%).';
COMMENT ON COLUMN CLOTHESSTORE.PRODUCT.IMAGEFRONT IS 'Base64 de la imagen frontal.';
COMMENT ON COLUMN CLOTHESSTORE.PRODUCT.IMAGEBACK IS 'Base64 de la imagen trasera.';
COMMENT ON COLUMN CLOTHESSTORE.PRODUCT.POPULARSEARCH IS 'Producto de búsqueda popular. No (0).';


-- DML
INSERT INTO CLOTHESSTORE.PRODUCT(NAME, DESCRIPTION, PRICE, RATEDISCOUNT, POPULARSEARCH) 
VALUES('Blusa', 'Blusa color sólido manga larga', 200.452,50,1);